const data = [
    {
        "length": 17,
        "height": 7,
        "borders":
            [
                "H2"
            ],
        "ground":
            [
                "A1",
                "B1",
                "C1",
                "D1",
                "E1",
                "F1",
                "G1",
                "H1",
                "I1",
                "J1",
                "K1",
                "L1",
                "M1",
                "N1",
                "O1",
                "P1",
                "Q1",
            ],
        "ladders":
            [
                "G3",
                "G2"
            ],
        "stars":
            [
                "H3"
            ],
        "yellow":
            [
                "C2"
            ],
        "green":
            [
                "D2"
            ],
        "red":
            [
                "E2"
            ],
        "spawn": "B2"
    }
];